from ..subcommands import Subcommand


TERMS = """
Wordfence CLI License Terms and Conditions

This Wordfence CLI License Terms and Conditions (“Agreement”) governs your use of Wordfence (as defined below) provided by Defiant Inc. (“Defiant” or the “Licensor”), to you (“you,” or “your”) for use pursuant to and subject to the licenses contained herein between Defiant Inc., you, your employer, and any other person or entity who owns or otherwise lawfully controls the computer on which the Wordfence CLI is installed (collectively “Licensee”).

BY CLICKING “I AGREE”, YOU REPRESENT THAT YOU ARE DULY AUTHORIZED BY LICENSEE TO (i) ACCESS AND USE THE WORDFENCE CLI; AND (ii) ACCEPT THIS AGREEMENT AND AGREE THAT YOU AND LICENSEE ARE LEGALLY BOUND BY IT. IF YOU OR LICENSEE DO NOT AGREE TO THE TERMS AND CONDITIONS OF THIS AGREEMENT AND THE TERMS AND CONDITIONS OF ANY APPLICABLE LICENSE AGREEMENTS OR NOTICES INDICATED OR REFERENCED BELOW, THEN YOU AND LICENSEE MAY NOT USE THE WORDFENCE CLI.

    1. DEFINITIONS

        1.1 “Affiliate” means, for a Party, any other entity that controls, is controlled by, or under common control with, the Party. For the purposes of this definition, the term “control” means the direct or indirect power to direct the affairs of the other entity through at least 50% of the shares, voting rights, participation, or economic interest in this entity.
        1.2 “Claim” means a claim, action, complaint, or legal regulatory body, administrative or judicial proceeding filed against a Party.
        1.3 “Computer” means a virtual or physical device for storing or processing data, such as servers, desktop computers, laptops, mobile devices and hardware products. Where a device contains more than one virtual environment (including virtual machines and virtual processors), each virtual environment will be counted as a separate Computer.
        1.4 “Licensee Data” means any information that is imported by or on behalf of Licensee into Wordfence from Licensee’s internal data stores or other third-party data providers, or is collected via the distributed code, in connection with Licensee’s use of Wordfence.
        1.5 “Licensee Site” means any current or future website or application, including the server on which the website or application is hosted, that is owned and operated by Licensee, or is hosted or operated by a third-party on Licensee’s behalf, and that contains a privacy policy or terms of use governing data collection practices that Licensee controls.
        1.6 “Effective Date” means the date this Agreement was agreed to by Licensee.
        1.7 “Data Protection Terms” means the applicable Standard Contractual Clauses found at https://www.wordfence.com/standard-contractual-clauses/ or as otherwise agreed by the Parties in writing.
        1.8 “Documentation” means the applicable technical specification and usage documentation for Wordfence CLI as such materials are made generally available on www.wordfence.com. “Documentation” does not include any third-party content posted to www.wordfence.com, content published in user forums hosted or moderated by Defiant, content related to any future functionality, or communications exchanged between Defiant and Licensee.
        1.9 “Ordering Document” means any Licensor invoice or order form which references this Agreement. Each Ordering Document which references this Agreement shall be deemed a part of this Agreement.
        1.10 “Party” means Defiant or Licensee, as applicable.
        1.11 “User” means an individual who may use or access Wordfence on behalf of Licensee.
        1.12 “Wordfence” means technology owned by Defiant or licensed to Defiant by a third-party consisting of the Wordfence API and the Wordfence CLI.
        1.13 “Wordfence API” means the Defiant controlled system access point and library function provided by Defiant-hosted servers that are accessible to the Wordfence CLI
        1.14 “Wordfence CLI Free” means the service and functionality described at https://www.wordfence.com/products/wordfence-cli/, provided by the installation and use of the Wordfence CLI and Wordfence API that are available without payment to Defiant.
        1.15 “Wordfence CLI” means the Python code, Bash code, Markdown, and other code provided by Defiant contained within the source code repository, Python package, or compiled binary executable.
        1.16 “Wordfence CLI Commercial” means the service and functionality of Wordfence CLI Free plus the additional functionality described at https://www.wordfence.com/products/wordfence-cli/, provided as a result of purchasing a license subscription from Defiant.

    2. PAYMENT, TERM, AND DELIVERY

        2.1 Wordfence CLI Commercial License Term. Each License Term for Wordfence CLI Commercial shall begin on the Effective Date and expire twelve (12) months thereafter (the “License Term”). All applicable fees for such renewals will be at Defiant’s then-current rates. If Licensee’s subscription is not renewed and all fees paid in full, Licensee’s access to the Wordfence CLI Commercial will terminate at the end of the then-current License Term.
        2.2 Wordfence CLI Commercial Fees and Payment. Prior to each License Term, Licensee shall pay all fees set forth on Defiant’s pricing page, https://www.wordfence.com/products/wordfence-cli/. Prices do not include applicable taxes.
        2.3 Wordfence CLI Commercial Refunds. In the event Licensee is not satisfied with Wordfence CLI Commercial, Licensee may terminate its use of Wordfence CLI Commercial within thirty (30) days of the Effective Date of the initial License Term and receive a full refund. If Licensee terminates more than 30 days after the Effective Date of the initial License Term, Licensee will not be entitled to a refund of any portion of the Fees and Licensee’s access to Wordfence CLI Commercial will be terminated immediately. Except as otherwise stated in these Terms, all fees paid for the Service are non-refundable.
        2.4 Wordfence CLI Free. Wordfence CLI Free is offered at no fee. Notwithstanding any other provision of this Agreement, Wordfence CLI Free is provided “AS IS” without warranty or support of any kind, express or implied. Defiant may terminate Licensee’s access to Wordfence CLI Free at any time for any reason and without liability of any kind. IF LICENSEE SUBSEQUENTLY PURCHASE A SUBSCRIPTION TO WORDFENCE CLI COMMERCIAL, LICENSEE’S ACCESS TO WORDFENCE CLI FREE SHALL IMMEDIATELY TERMINATE AND LICENSEE EXPRESSLY AGREES THAT, UNLESS LICENSEE HAS A SEPARATE SIGNED AGREEMENT GOVERNING LICENSEE’S ACCESS TO AND USE OF WORDFENCE, THIS AGREEMENT, AND THE TERMS AND CONDITIONS HEREIN, SHALL GOVERN LICENSEE’S USE OF WORDFENCE CLI COMMERCIAL.
        2.5 Electronic Delivery. Wordfence and all Documentation shall be delivered by electronic means. Wordfence shall be deemed delivered when it is made available for download by Licensee.

    3. LICENSE AND RESTRICTIONS

        3.1 License Grant for the Wordfence CLI. The Wordfence CLI made available by Defiant is provided to Licensee under the terms and conditions of the GNU General Public License version 3 (“GPL”). Licensee can redistribute it and/or modify the Wordfence CLI under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at Licensee’s option) any later version.
            Licensee should receive a copy of the GPL along with the Wordfence CLI. If not, a copy of the GPL is available at https://www.gnu.org/licenses/gpl-3.0.en.html. For purposes of the GPL, “Program” will mean the Wordfence CLI. To the extent there is a conflict between the terms and conditions of this Agreement and the GPL, the terms and conditions of the GPL shall prevail.
            The Wordfence CLI is distributed WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
            With respect to the Wordfence CLI, to the extent that the terms and conditions of the GPL conflict with the terms of this Agreement, the GPL will prevail.
        3.2 License Grant for the Wordfence API. Subject to License’s compliance with all of the terms and conditions of this Agreement, and during the applicable License Term, Defiant grants Licensee a limited, worldwide, non-transferable, non-sublicensable, non-exclusive license to use the Wordfence API for Licensee’s internal business purposes in connection with Licensee’s own use of the Wordfence CLI, but only in accordance with: (a) the Documentation; (b) the restrictions in Section 3.3, or (c) any other restrictions mutually agreed upon by Licensee and Defiant.
        3.3 Licensee Site Scan Limits. Licensees of Wordfence CLI Commercial are permitted to scan the number of Licensee Sites set forth in the Licensee’s executed Ordering Document. Licensees of Wordfence CLI Free are permitted to scan an unlimited number of Licensee Sites. The number of Licensee Sites a Licensee is permitted to scan shall be referred to as the “Site Scan Limit.”
        3.4 License Conditions. Except to the extent expressly permitted under this Agreement, Licensee agrees as a condition of the licenses that it must not:
            (A) use Wordfence in (1) violation of any applicable law or regulation (including, where applicable, the EU and UK General Data Protection Regulation and the California Consumer Privacy Act), or in connection with unlawful material (such as material that violates any obscenity, defamation, harassment, privacy, publicity or intellectual property laws); or (2) a manner that would cause a material risk to the security or operations of Defiant or any of its customers, or to the continued normal operation of other Defiant customers.
            (B) distribute, republish, transmit, sell, rent, lease, host, or sub-license Wordfence;
            (C) copy, use, download, or display Wordfence except as specifically authorized in this Agreement; or
            (D) offer, use, or permit the use of Wordfence in a computer service business, third-party outsourcing service, on a membership or subscription basis, on a service bureau basis, on a time-sharing basis, as part of a hosted service, or on behalf of any third-party.
            Defiant reserves all other rights not expressly granted in this Agreement.
        3.5 Defiant Ownership. Notwithstanding anything to the contrary contained herein, except for the limited license rights expressly provided herein, Defiant and its licensors have and will retain all rights, title and interest (including, without limitation, all patent, copyright, trademark, trade secret and other intellectual property rights) in and to Wordfence, any information available through the Wordfence API, and all copies, modifications and derivative works thereof (including any changes which incorporate any of Licensee’s ideas, feedback or suggestions). Licensee acknowledges that Licensee are obtaining only a limited license right to Wordfence and that irrespective of any use of the words “purchase”, “sale” or like terms hereunder no ownership rights are being conveyed to Licensee under this Agreement or otherwise.
        3.6 Third-Party Providers. Licensee is responsible for complying with any applicable terms and conditions of any third-party data, products, services, and platforms used by Licensee in conjunction with Wordfence.
        3.7 Privacy Policy and Data Protection Terms. Licensee’s use of Wordfence is subject to the Wordfence Privacy Policy, a current version of which is available here: https://www.wordfence.com/privacy-policy/ and the Data Protection Terms.

    4. THIRD-PARTY ACCESS

        4.1 Outsourcing and Third-Party Access. Licensee may allow a third-party contractor to operate, use or access Wordfence solely on Licensee’s behalf, provided such use or access is only for Licensee’s internal business purposes. Licensee is responsible for ensuring that any third-party operating, using or accessing Wordfence on Licensee’s behalf complies with the terms of this Agreement. Licensee is responsible for and liable for the acts or omissions of such third-party as if they were Licensee’s acts or omissions.

    5. CUSTOMER CONTENT AND CUSTOMER DATA

        5.1 Licensee Ownership. As between Defiant and Licensee, Licensee owns (or where applicable, must ensure it has a valid license to) the Licensee Data, subject to Defiant’s underlying intellectual property rights in Wordfence.
        5.2 Permitted Use. Licensee grants Defiant and its Affiliates a non-exclusive, worldwide, royalty-free license to use, copy, transmit, sub-license, index, store, distribute, and display Licensee Data : (1) to the extent necessary to perform its obligations or enforce its rights under this Agreement; (2) for the purposes of developing, modifying, improving, supporting, customizing, and operating Wordfence; or (3) where required or authorized by law.
        5.3 Responsibility.
            (A) Licensee will conspicuously display a privacy policy that discloses Licensee’s privacy practices, identifies the collection, use and sharing of information gathered in connection with Wordfence, including types of data collected, and offers an opportunity to opt out of (or opt-in if applicable law requires) the collection, use and sharing of data gathered in connection with Wordfence.
            (B) Licensee retains complete control over the installation and configuration of the Wordfence CLI, and all Licensee Sites. Licensee must comply with its privacy policy, and is responsible for ensuring that all Licensee Sites used with the Wordfence CLI and all Licensee Data comply with all applicable laws and regulations. Licensee will take reasonable steps to identify and promptly remove any Licensee Data that violates the requirements of Section 5.3(A) (“Unlawful Content”), in accordance with applicable laws and regulations. If there is Unlawful Content, Defiant may suspend services and remove the Unlawful Content.
        5.4 Prohibited Actions. The following actions are prohibited and constitute a material breach of this Agreement. If any of these prohibitions conflict with the terms of the GPL, where applicable, the GPL will prevail. This list is not meant to be exhaustive. By way of example, and not as a limitation, Licensee will not:
            (A) Use Wordfence in excess of the Site Scan Limit set forth in Section 3.3.
            (B) Use Wordfence for any purpose or to take any actions in violation of local, state, national or international laws, regulations, codes or rules.
            (C) Take any action that places an unreasonable or disproportionately large load on Defiant’s infrastructure or otherwise that may adversely affect performance of Wordfence or restrict any other customer or Defiant from using Wordfence.
            (D) Use Wordfence for unauthorized framing or linking, or via automated devices, bots, agents, crawl, scraping, scripts, intelligent search or any similar means of access to Wordfence.
            (E) Aggregate, copy, duplicate, publish or make available the Wordfence API or any information available through the Wordfence API to third parties in any manner.
            (F) Defame, abuse, harass, stalk, threaten or otherwise violate the legal rights (such as rights of privacy or publicity) of others, or impersonating anyone else or misrepresenting Licensee’s identity of affiliation.
            (G) Publish, post, upload, distribute or disseminate any inappropriate, profane, defamatory, pornographic, offensive, harassing, infringing, obscene, indecent or unlawful topic, name, material, content or information.
            (H) Upload or download files that contain software or other material protected by intellectual property laws or other laws, unless Licensee owns or controls the rights, titles, or interests thereto or have received all necessary consents or rights.
            (I) Upload or transmit files that contain viruses, mal-ware, disabling code, corrupted files, or any other similar software or programs that may damage the operation of another’s computer.
            (J) Use Wordfence to make available unsolicited advertising or promotional materials, spam, pyramid schemes, chain letters, or similar forms of unauthorized advertising or solicitation.
            (K) Harvest or otherwise collect information about others, including without limitation email addresses or other contact information, without their consent, or hack or violate any security measures.
            (L) Falsify or delete any author attributions, legal or other notices, or proprietary designations or labels of origin or source.
            (M) Engage in any other action that, in the judgment of Defiant, exposes it or any third party to potential liability or detriment of any type.

    6. WORDFENCE CLI COMMERCIAL SUPPORT

        We provide support for Wordfence CLI Commercial via email only; we do not offer support for Wordfence CLI Free. We do not guarantee a specific response time and we do not provide a service level agreement. In general, we operate weekdays from Monday to Friday, 9 a.m. to 8 p.m. ET excluding holidays. We will try to respond to email inquiries within one business day. Support is offered on a per user basis and not a per license basis. This means that we limit the amount of support we provide per paid license. Our support offered for Wordfence CLI Commercial is limited to 2 hours of support per incident. We reserve the right to decline further support or to charge for additional support beyond the 2 hours of support. We endeavor to provide you with excellent customer service, but we reserve the right to immediately terminate service without a refund if a user is insulting, threatening, or abusive to our support team, or violates this Agreement. We do not provide support for issues that are not directly related to the Wordfence CLI Commercial, such as website configuration.

    7. DISCLAIMER OF LIABILITY

        TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL DEFIANT OR ITS AFFILIATES, OR ANY OF ITS OR THEIR RESPECTIVE LICENSORS OR SERVICE PROVIDERS, BE LIABLE TO LICENSEE FOR ANY USE, INTERRUPTION, DELAY, OR INABILITY TO USE WORDFENCE. LICENSEE IS PROVIDED WORDFENCE PURSUANT TO WORDFENCE LICENSE TERMS AND CONDITIONS BETWEEN LICENSOR AND LICENSEE, SOLELY FOR THE BENEFIT OF LICENSEE AND AT LICENSEE’S DISCRETION. LICENSEE ACKNOWLEDGES THAT LICENSEE HAS NO RIGHTS UNDER THAT AGREEMENT INCLUDING ANY RIGHTS TO ENFORCE ANY OF ITS TERMS. ANY OBLIGATION OR LIABILITY LICENSOR OR ITS AFFILIATES, OR ANY OF ITS OR THEIR LICENSORS OR SERVICE PROVIDERS, MAY HAVE WITH RESPECT TO LICENSEE’S USE OR INABILITY TO USE WORDFENCE SHALL BE SOLELY TO LICENSEE PURSUANT TO THAT AGREEMENT AND SUBJECT TO ALL LIMITATIONS OF LIABILITY SET FORTH THEREIN.
        7.1 Disclaimer of Warranties
            TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, WORDFENCE IS PROVIDED “AS IS,” “WITH ALL FAULTS,” AND “AS AVAILABLE,” AND THE ENTIRE RISK OF USE AND PERFORMANCE REMAINS WITH LICENSEE. DEFIANT AND ITS AFFILIATES AND LICENSORS DO NOT MAKE ANY REPRESENTATIONS, WARRANTIES, OR CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY AND HEREBY DISCLAIM ANY IMPLIED WARRANTIES OF MERCHANTABILITY, MERCHANTABLE QUALITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, QUIET ENJOYMENT, OR NON-INFRINGEMENT, AND WE MAKE NO REPRESENTATION OR WARRANTY THAT THE WORDFENCE: (A) WILL MEET LICENSEE’S NEEDS OR EXPECTATIONS; (B) WILL BE AVAILABLE OR PROVIDED ON AN UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE BASIS; (C) WILL BE ACCURATE, COMPLETE, OR RELIABLE, OR (D) WILL BE FREE FROM VIRUSES, WORMS, OR OTHER HARMFUL OR MALICIOUS COMPONENTS, NOR DO WE WARRANT THAT ANY DEFECTS OR ERRORS WITH THE WORDFENCE WILL BE CORRECTED.
        7.2 Disclaimer of Certain Damages
            TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL WE OR OUR AFFILIATES, SUPPLIERS, OR LICENSORS BE LIABLE FOR ANY CONSEQUENTIAL, SPECIAL, INCIDENTAL, INDIRECT, OR PUNITIVE DAMAGES; FOR LOSS OF PROFITS; LOSS OR CORRUPTION OF DATA OR OTHER INFORMATION; OR ANY OTHER LOSS OR ANY KIND, WHETHER FORESEEABLE OR NOT, BASED ON, RESULTING FROM, ARISING OUT OF, OR IN ANY WAY CONNECTED WITH WORDFENCE OR THESE TERMS, EVEN IF WE OR ANY OF OUR AFFILIATES, SUPPLIERS, OR LICENSORS HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
        7.3 LIMITATION OF LIABILITY AND EXCLUSIVE REMEDY.
            TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW AND TO THE EXTENT THEY ARE NOT EXCLUDED OR DISCLAIMED UNDER THE DISCLAIMER OF WARRANTIES OR DISCLAIMER OF CERTAIN DAMAGES SECTIONS, OUR MAXIMUM, AGGREGATE LIABILITY TO LICENSEE, AND LICENSEE’S EXCLUSIVE REMEDY UNDER THESE TERMS FOR ANY AND ALL DAMAGES, INJURIES, AND LOSSES ARISING FROM ANY AND ALL CLAIMS AND CAUSES OF ACTION ARISING OUT OF, BASED ON, RESULTING FROM, OR IN ANY WAY RELATED TO THESE TERMS OR WORDFENCE WILL NOT EXCEED THE MONIES PAID BY LICENSEE TO DEFIANT IN THE 12 MONTHS PRECEDING THE RELEVANT CLAIM OR $10, WHICHEVER IS GREATER. THE EXISTENCE OF MULTIPLE CLAIMS OR SUITS UNDER OR RELATED TO THESE TERMS OR THE SITE WILL NOT ENLARGE OR EXTEND THE LIMITATION OF MONEY DAMAGES.
        7.4 Independent Remedies. The Disclaimer of Certain Damages Section is independent of Licensee’s exclusive remedy in the Limitation of Liability and Exclusive Remedy Section and it survives even if the exclusive remedy fails of its essential purpose or otherwise is deemed unenforceable. Each of the limitations of liability above apply without regard to whether loss, liability, or damage arise from (a) breach of contract, (b) breach of warranty, (c) fault or tort, including negligence and misrepresentation, (d) strict liability, or (e) any other cause of action, to the extent the exclusions and limitations are not prohibited by applicable law.
        7.5 Indemnity. Licensee will defend, indemnify and hold harmless Defiant, its officers, directors, employees and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney’s fees) arising from: (i) Licensee’s use of and access to Wordfence, including any data or content transmitted or received by Licensee; (ii) Licensee’s violation of these Terms; or (iii) Licensee’s violation of any third-party rights, including without limitation any privacy, security, or intellectual property rights.
        7.6 Agreement to Arbitrate; Class Action Waiver; and Location of Dispute Resolution. Any dispute, controversy or claim between or among the parties arising out of or relating to this Agreement, or the breach, termination or validity thereof, including the determination of the scope or applicability of the agreement to arbitrate, shall be settled by arbitration administered by the American Arbitration Association in accordance with its Commercial Arbitration Rules. The arbitration shall be conducted in English in Seattle, Washington.

    8. TERMINATION

        8.1 Termination With or Without Cause
            (A) Material Breach by Either Party. If either Party commits a material breach of this Agreement, the non- breaching Party may give written notice describing the nature and basis of the breach to the breaching Party. If the breach is not cured within 10 days of the notice date, the non-breaching Party may immediately terminate this Agreement.
            (B) Other Breaches. Defiant may terminate this Agreement immediately upon written notice to Licensee, if required by law; or Licensee breaches section 3.3 of this Agreement.
            (C) Without Cause. Defiant may terminate this Agreement, without cause, by providing the Licensee with a notice of termination at least five days prior to the effective date of such termination.
        8.2 Effect of Termination or Expiration.
            (A) Upon termination or expiration of this Agreement or any License Term for Wordfence the licenses and associated rights to Wordfence will immediately terminate.
            (B) If Defiant reasonably determines that Licensee’s deployment of Wordfence is causing a material risk to the security or operations of Defiant or any of its customers or to the continued normal operation of other Defiant customers (each a “Deployment Risk”), then Defiant may, at any time, upon written notice to Licensee:
                (1) immediately suspend Licensee’s access, in whole or in part, to Wordfence, until such Deployment Risk is resolved; or
                (2) as a final option, Defiant may terminate the Licensee’s use of Wordfence.
        8.3 Survival. The termination or expiration of this Agreement will not affect any provisions of this Agreement which by their nature survive termination or expiration, including the provisions that deal with the following subject matters: definitions, payment obligations, confidentiality, term and termination, effect of termination, intellectual property ownership, permitted use, license compliance, limitation of liability, privacy, usage analytics and the “General Provisions” section in this Agreement.

    9. GENERAL PROVISIONS
        9.1 Assignment.
            (A) Licensee may assign this Agreement in its entirety to a surviving person or entity under a merger or acquisition of Licensee, upon written notice to Defiant if the assignment does not expand the scope of the license granted in Wordfence and if the assignee agrees in writing, for the benefit of Defiant, to assume all of Licensee’s obligations under this Agreement.
            (B) Defiant may assign this Agreement or delegate its obligations, in whole or in part, to its Affiliates or in connection with a merger, change of control, or acquisition of Defiant or the assets of the business to which this Agreement relates, upon written notice to Licensee.
            (C) Except as provided in this section 9.1 (Assignment), Licensee may not assign, voluntarily, by operation of law or otherwise, any rights or obligations under this Agreement without the prior, written consent of Defiant.
            (D) Any (attempted) assignment in derogation of this section will be null and void.
        9.2 Governing Law, Venue. This Agreement is governed by and construed under the laws of the State of Washington, without regard to any conflict of law rules or principles, and excluding the application of the United Nations Convention on Contracts for the International Sale of Goods. The Parties irrevocably submit to the exclusive jurisdiction of the courts of competent jurisdiction in the County of King, State of Washington, provided however, Defiant will have the right to pursue Claims against Licensee in any other jurisdiction worldwide to enforce its rights under this Agreement or to enforce its intellectual property rights.
        9.3 Force Majeure. Neither Party is liable for failure to perform its obligations under this Agreement (except for any payment obligations) to the extent that performance is delayed, prevented, restricted or interfered with as a result of any causes beyond its reasonable control, including acts of God, terrorism, labor action, fire, flood, earthquake, pandemic, denial of service attacks and other malicious conduct, utility failures, power outages, or governmental acts, orders, or restrictions.
        9.4 Injunctive Relief. Actual or threatened breach of certain sections of this Agreement (such as, without limitation, provisions on intellectual property (including ownership), license, privacy, data protection and confidentiality) may cause immediate, irreparable harm that is difficult to calculate and cannot be remedied by the payment of damages alone. Either Party will be entitled to seek preliminary and permanent injunctive relief and other equitable relief for any such breach.
        9.5 Notices. Any notice given under this Agreement must be in writing by email to the following addresses (or addresses notified in writing by either Party): (A) to Defiant at privacy@defiant.com and (B) to Licensee at Licensee’s email address as registered on wordfence.com.
        9.6 No Agency. Nothing in this Agreement is intended to constitute a fiduciary relationship, agency, joint venture, partnership, or trust between the Parties. No Party has authority to bind the other Party.
        9.7 Waiver, Modification. Neither Party’s waiver of the breach of any provision constitutes a waiver of that provision in any other instance. This Agreement may not be modified nor any rights under it waived, in whole or in part, except in writing signed by the Parties.
        9.8 Entire Agreement. This Agreement and the GPL, as applicable to the Wordfence CLI, contains the entire understanding of the Parties relating to the subject matter and supersedes all earlier agreements, understandings, proposals, discussions, negotiations, representations and warranties, both written and oral, regarding the subject matter.
        9.9 Counterpart. This Agreement (or a component) may be executed in one or more counterparts, each of which constitutes an original and all of which taken together constitutes the same agreement. Each Party may sign this Agreement using an electronic or handwritten signature, which are of equal effect, whether on original or electronic copies.
        9.10 Severability. If any term of this Agreement is held invalid or unenforceable for any reason, the remainder of the term and this Agreement will continue in full force and effect.
        9.11 Trade Rules. Licensee acknowledges that Wordfence may be subject to trade control laws and regulations, and Licensee will comply with them.
        9.12 U.S. Government Licensing. For US Government end users: Licensee acknowledges that Wordfence are “Commercial Item(s),” as that term is defined at 48 C.F.R. section 2.101, consisting of “Commercial Computer Software” and “Commercial Computer Software Documentation,” as the terms are used in 48 C.F.R. section 12.212 or 48 C.F.R. section 227.7202, as applicable. Licensee agrees, consistent with 48 C.F.R. section 12.212 or 48 C.F.R. sections 227.7202-1 through 227.7202-4, as applicable, the Commercial Computer Software and Commercial Computer Software Documentation are being licensed to U.S. Government end users (A) only as Commercial Items; and (B) with only those rights as are granted to all other end users pursuant to the terms and conditions herein. Unpublished rights are reserved under the copyright laws of the United States.
"""  # noqa: E501


class TermsSubcommand(Subcommand):

    def invoke(self) -> int:
        print(TERMS)
        return 0


factory = TermsSubcommand
